### ISSUE TITLE
centos-quarkus-maven image question

### ISSUE THREAD

**Issue by vaughnmb** [quarkusio/quarkus-images#169]
Will the centos-quarkus-maven image be updated to use Java 16/17 or should I be using some other quarkus based image?

**Comment by cescoffier** [comment]
The centos-quarkus-maven is not going to be updated. It's already in maintenance mode. 
The other images will be updated as soon as we have the GraalVM / Mandrel versions.

**Comment by vaughnmb** [comment]
And by other images are you referring to   quay.io/quarkus/ubi-quarkus-mandrel?

**Comment by cescoffier** [comment]
These:
```
docker pull quay.io/quarkus/ubi-quarkus-native-image:VERSION
docker pull quay.io/quarkus/ubi-quarkus-mandrel:VERSION
docker pull quay.io/quarkus/ubi-quarkus-native-s2i:VERSION
docker pull quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0
```

**Comment by cescoffier** [comment]
The problem with the centos one is that it contains many different tools. It's very hard to keep everything up to date and every time we update one, we broke something. I know it's a convenient image, but I recommend building your own with the tools you need, so an update won't break on your side.

**Comment by nicolas-vivot** [comment]
why the tool image containing maven, graalvm, buildah and postman does not contains postman-docker with the necessary settings so that it can be used for CI ?

I understand the point that it can be "hard" to maintain, but at the same time, we (Quarkus users) are spending a lot of time to redo what you (redhat) have probably already done.

**Comment by cescoffier** [comment]
First, I didn't know about postman-docker.

Actually, no it's not already done. We don't use this image on CI. It was initially done for Tekton, but that approach got abandoned. 

Note that the s2i image contains Maven, Gradle, and GraalVM, which is in general what you would use. What's your requirement regarding container image creation? Asking, because I believe we should provide _something_, but most probably from the Quarkiverse and built slightly differently than this image.

**Comment by nicolas-vivot** [comment]
Ok, understand better.

I'm using Quarkus on production for two years now, using the provided runtime image (the distroless native one)

For building, i'm using my own image (java base image with maven & graalvm installed) and since i'm on gitlab i'm using the shared runners there with... docker in docker!

For the reasons we all know, i want to leave from DinD and therefore i have just replaced the usage of Docker for the image build part by Kaniko.
Now, the only remaining part using DinD in my pipelines is the Quarkus build itself, since i'm using the TestContainers for some of my tests.

Therefore, instead of continuing to build my own image for builds, i started to have a look at what already exists and found two things:

- this repository, providing the different images, including the one with all the tools we need to build a Quarkus app without docker
- a quite recent blog [here](https://quarkus.io/blog/quarkus-devservices-testcontainers-podman/) talking about how to setup podman to take over docker so that the quarkus dev services works in an environment without docker (while potentially waiting for either some improvement on Quarkus or Podman to better integrate within the test containers / dev services feature)

**Comment by nicolas-vivot** [comment]
Do you think an update to add the podman-docker package & configure the few things mentioned in the blog is something doable ?

**Comment by cescoffier** [comment]
Definitely! 
Fancy a PR?

**Comment by nicolas-vivot** [comment]
Since i'm not able to build this project from my station, i won't sorry.

**Comment by cescoffier** [comment]
Closing - the tooling image is abandoned.
